[app]
name = "demo-app"
version = "1.0.0"

[server]
host = "localhost"
port = 8080
timeout = 30

[database]
host = "localhost"
port = 5432
name = "demo_db"
pool_size = 10

[features]
enable_auth = true
enable_caching = false
debug_mode = false