[server]
host = "0.0.0.0"
port = 3000

[database]
host = "prod-db.example.com"
password = "secret123"

[features]
enable_caching = true
maintenance_mode = true

[logging]
level = "info"
format = "json"