
[app]
  name = "demo-app"
  version = "1.0.0"

[database]
  host = "prod-db.example.com"
  name = "demo_db"
  password = "secret123"
  pool_size = 10
  port = 5432

[features]
  debug_mode = false
  enable_auth = true
  enable_caching = true
  maintenance_mode = true

[logging]
  format = "json"
  level = "info"

[server]
  host = "0.0.0.0"
  port = 3000
  timeout = 30
